### PR TITLE
Resolved set of issues

### PR DESCRIPTION
**Pull request by igor-ivanov**
@miked-mellanox could you review

### CODE REVIEW

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-libibprof-pr/7/
Test PASSed.

**Comment by igor-ivanov** [comment]
I noticed this code too but did not touch it this time

**Comment by mike-dubman** [comment]
could you please than fix it in another pr

**Pull request merged**
