### PR TITLE
Update README with IBPROF_WARMUP_NUMBER description

### PR DESCRIPTION
**Pull request by igor-ivanov**
Signed-off-by: Igor Ivanov igor.ivanov.va@gmail.com

### CODE REVIEW

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mike-dubman** [comment]
@igor-ivanov - plz rebase

**Comment by Di0gen** [comment]
bot:retest

**Comment by Di0gen** [comment]
bot:retest

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libibprof-pr/4/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libibprof-pr/5/ for details (Mellanox internal link).

**Pull request merged**
