### PR TITLE
Fix a bug with long name passed to ibprof_interval_start()

### PR DESCRIPTION
**Pull request by igor-ivanov**

### CODE REVIEW

**Comment by mike-dubman** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libibprof-pr/2/ for details (Mellanox internal link).

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libibprof-pr/6/ for details (Mellanox internal link).

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-libibprof-pr/8/ for details (Mellanox internal link).

**Pull request merged**
