### PR TITLE
Add PMIx API support

### PR DESCRIPTION
**Pull request by igor-ivanov**
@miked-mellanox could you look and accept

### CODE REVIEW

**Comment by mike-dubman** [comment]
please fix ./contrib/jenkins/test_jenkins.sh to use proper module (hpcx-gcc?)

**Comment by igor-ivanov** [comment]
@miked-mellanox I do not understand you. Do you mean supression warning as '(col. 1) remark: loops in this subroutine are not good vectorization candidates (try compiling with O3 and/or IPO)' from intel compiler.

**Comment by mike-dubman** [comment]
- jenkins complains on this:

``` shell
20:01:05 + module load mlnx-hpc-latest/gcc/ompi-1.8
20:01:05 ++ /usr/bin/modulecmd bash load mlnx-hpc-latest/gcc/ompi-1.8
20:01:05 ModuleCmd_Load.c(204):ERROR:105: Unable to locate a modulefile for 'mlnx-hpc-latest/gcc/ompi-1.8'
20:01:05 + eval
20:01:05 + mkdir -p /var/lib/jenkins/jobs/gh-libibprof-pr/workspace/install/bin
20:01:05 + mpicc -o /var/lib/jenkins/jobs/gh-libibprof-pr/workspace/install/bin/mpi_hello mpi_hello.c
20:01:05 ./contrib/jenkins/test_jenkins.sh: line 137: mpicc: command not found
20:01:05 Build step 'Execute shell' marked build as failure
20:01:05 TAP Reports Processing: START
20:01:05 Looking for TAP results report in workspace using pattern: **/*.tap
20:01:05 Saving reports...

```

**Comment by igor-ivanov** [comment]
ahh, ok

**Comment by igor-ivanov** [comment]
@miked-mellanox  I do not see any 'load mlnx-hpc-latest/gcc/ompi-1.8' lines in libibprof/test_jenkins.sh
May be jenkins has old script for libibprof?

**Comment by mike-dubman** [comment]
plz see here: 
https://github.com/mellanox-hpc/libibprof/pull/5

**Comment by igor-ivanov** [comment]
@miked-mellanox understand now thanks. Looked at bgate/hpc_jenkins before.

**Comment by igor-ivanov** [comment]
@miked-mellanox what is a status of this PR?

**Comment by mike-dubman** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
PR https://github.com/mellanox-hpc/libibprof/pull/5 should be applied before this PR to get PASS result

**Comment by mike-dubman** [comment]
bot:retest

**Pull request merged**
